name: Publish docs via GitHub Pages

on: [push, pull_request]

jobs:

  mkdocs_build_test_deploy:
    
    name: build mkdocs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # required to use caching because it depends on requirements.txt
      - name: create requirements
        run: |
          python -m pip install --upgrade pip
          pip install pip_tools
          pip-compile setup.cfg --extra docs

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'

      - name: Install package and deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .

      - name: build docs
        run: mkdocs build -f mkdocs.yml

      - name: deploy mkdocs
        if: success() && github.event_name == 'push' && github.ref_name == 'main'
        run: mkdocs gh-deploy -f mkdocs.yml
