name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - mkdocs_setup

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install package and deps
        run: |
          python -m pip install --upgrade pip
          pip install .[docs]

      - name: Deploy docs
        run: mkdocs gh-deploy -f mkdocs.yml -b mkdocs_setup
